### PR TITLE
Server test

### PR DESCRIPTION
**Pull request by RobinBurri**
This is the hello world server I used when I want to test my classes.
It is in serverTest/serverTest.cpp
I don't think it needs code review as I won't be in our real webserver project.
It uses the class Socket that can be reviewed.
the purpose of serverTest is to be called in webserver() so we can have a basic fully working web server when all my pull requests will be merged in stage.

* [x] Waiting on #22

### CODE REVIEW

**Comment by RobinBurri** [comment]
I added serverTest.cpp to Makefile and Socket.cpp too. But this is not supposed to work on its own. It needs Request and Response. It will work once merged with the rest.

**Comment by t-h2o** [comment]
That does not compile
```
$ make test
src/serverTest/serverTest.cpp:1:10: fatal error: 'Request.hpp' file not found
#include "Request.hpp"
         ^~~~~~~~~~~~~
1 error generated.
```

**Review by t-h2o — DISMISSED** [review]

**Comment by t-h2o** [comment]
That doesn't compile
```
$ make
src/serverTest/serverTest.cpp:2:10: fatal error: 'Response.hpp' file not found
#include "Response.hpp"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [obj/serverTest/serverTest.o] Error 1
```

File: src/Socket/Socket.cpp [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+void
+Socket::test_socket(int item_to_test, const char *msg)
+{
+	if (item_to_test < 0)
+	{
+		std::cerr << msg << std::endl;
+		close(_sock_id);
+		throw Socket::SocketException();
+	}
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:45]: How work this test ?

File: src/Socket/Socket.cpp [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+Socket::create_socket(int domain, int type, int protocol)
+{
+	_sock_id = socket(domain, type, protocol);
+	test_socket(_sock_id, "create_socket() Fail!");
+}
+
+void
+Socket::binding_socket()
+{
+	_connection = bind(_sock_id, (struct sockaddr *)&_address, sizeof(_address));
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:25]: How can we use `cpp` cast instead of `c` cast?

File: inc/Socket.hpp [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+	void			   create_socket(int domain, int type, int protocol);
+	void			   binding_socket();
+	void			   start_listening();
+	void			   test_socket(int item_to_test, const char *);
+	void			   set_socket_non_blocking();
+
+  public:
+	Socket(int domain, int port, int type, int protocol, u_long interface);
+	int				   get_sock_id() const;
+	unsigned short int get_port() const;
```
[the remark this answers is not in the document]
Comment (RobinBurri) [reply inc/Socket.hpp]: [changed int port to unsigned short port](https://github.com/t-h2o/webserv/pull/23/commits/9147e9b36439f132ed0014ee085136e3fac15314)

File: inc/Socket.hpp [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+
+	class SocketException : public std::exception
+	{
+	  public:
+		const char *what() const throw();
+	};
```
[the remark this answers is not in the document]
Comment (RobinBurri) [reply inc/Socket.hpp]: NO, deleted.
3371d169ce581422ebd9ceb7a64b0ae7c9729762

File: src/Socket/Socket.cpp [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+	// Following code only working after select() is implemented
+	// ret = fcntl(_sock_id, F_SETFL, O_NONBLOCK);
+	// test_socket(ret, "fcnt() Fail!");
+}
+
+const char *
+Socket::SocketException::what() const throw()
+{
+	return "Exception: Socket set up failed.";
+}
```
[the remark this answers is not in the document]
Comment (RobinBurri) [reply src/Socket/Socket.cpp]: ok

File: inc/Socket.hpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (t-h2o) [reply inc/Socket.hpp]: Great

File: inc/Socket.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (t-h2o) [reply inc/Socket.hpp]: Great, do not forget to change in `Socket::test_socket`

File: src/Socket/Socket.cpp (hunk 1 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp:45]: it just checks that the value is not negative as it means an error from socket(), bind(), listen(), fcntl() and setsockopt().

File: src/Socket/Socket.cpp [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+{
+	_connection = bind(_sock_id, (struct sockaddr *)&_address, sizeof(_address));
+	test_socket(_connection, "binding_socket() Fail!");
+}
+
+void
+Socket::start_listening()
+{
+	int res;
+	res = listen(_sock_id, 10);
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:33]: Why 10 ?

From `man 3 listen`:
The backlog argument provides a hint to the implementation which the implementation shall use to limit the number of outstanding connections in the socket's listen queue.

File: src/Socket/Socket.cpp (hunk 2 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp]: changed.
66ba25bb4fc282d2087625a0cabe6bbc42ec827b

File: src/serverTest/serverTest.cpp [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+		req.parse_buffer(buffer);
+		if (req.get_method() == "POST")
+		{
+			while (recv_return > 0)
+			{
+				if (buffer[recv_return - 1] == '\n' || recv_return < MAXLINE)
+				{
+					break;
+				}
+				memset(buffer, 0, MAXLINE);
```
Comment (t-h2o) [inline src/serverTest/serverTest.cpp:51]: Use [`std::memset`](https://en.cppreference.com/w/cpp/string/byte/memset) ?

File: inc/Socket.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (RobinBurri) [reply inc/Socket.hpp]: Yes it has been changed later : 66ba25b

File: src/serverTest/serverTest.cpp [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+		std::cout << "***************** HTTP REQUEST START****************" << std::endl;
+		std::cout << req << std::endl;
+		std::cout << "***************** HTTP REQUEST END ****************\n";
+
+		res.load_http_request(req);
+		// std::cout << "***************** HTTP REPONSE START****************" << std::endl;
+		// std::cout << res << std::endl;
+		// std::cout << "***************** HTTP REPONSE END ****************\n" << std::endl;
+
+		std::string response = res.get_http_response();
```
Comment (t-h2o) [inline src/serverTest/serverTest.cpp:64]: A bit shorter...
```suggestion
		std::string response(res.get_http_response());
```

File: src/serverTest/serverTest.cpp [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+	 *	AF_INET for IPv4,
+	 *	Port number,
+	 *	SOCK_STREAM bidirectional byte-stream socket,
+	 *	AF_INET + SOCK_STREAM always protocol = 0,
+	 *	address for this socket, let the OS choose = INADDR_ANY
+	 */
+	const int				 MAXLINE = 1000;
+	Socket					 sock(AF_INET, 8080, SOCK_STREAM, 0, INADDR_ANY);
+	int						 connection_fd;
+	char					 buffer[MAXLINE] = { 0 };
```
Comment (t-h2o) [inline src/serverTest/serverTest.cpp:21]: I'm not sure, but perhaps it's better to set memory to 0 with `memset`.

File: src/Socket/Socket.cpp (hunk 6 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp:33]: no reason, I had to choose a number.

File: src/serverTest/serverTest.cpp (hunk 7 above)
Comment (RobinBurri) [reply src/serverTest/serverTest.cpp]: 10a0f15613e81ff8695aff60bd543f7ac1195d5910a0f15613e81ff8695aff60bd543f7ac1195d59 done.

File: src/serverTest/serverTest.cpp (hunk 9 above)
Comment (RobinBurri) [reply src/serverTest/serverTest.cpp:21]: ok will see for next version

File: src/Socket/Socket.cpp [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+void
+Socket::test_socket(int item_to_test, const char *msg)
+{
+	if (item_to_test < 0)
+	{
+		std::cerr << msg << std::endl;
+		close(_sock_id);
+		throw std::runtime_error("Exception: Socket set up failed.");
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:44]: What do you think about print the message once in the exception ?
```suggestion
		close(_sock_id);
		throw std::runtime_error(msg);
```

Comment (RobinBurri) [reply src/Socket/Socket.cpp]: yes of course

File: src/Socket/Socket.cpp (hunk 6 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp]: create macro LISTEN_BACKLOG for listen()
e9bc0f83a1cd315965451311e8c382d0d4d35ff2

**Comment by t-h2o** [comment]
That miss the [`<cstring>`](https://en.cppreference.com/w/cpp/string/byte/memset) header

```
src/serverTest/serverTest.cpp: In function ‘void serverTest()’:
src/serverTest/serverTest.cpp:51:38: error: ‘memset’ is not a member of ‘std’; did you mean ‘wmemset’?
   51 |                                 std::memset(buffer, 0, MAXLINE);
      |                                      ^~~~~~
      |                                      wmemset
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:64: obj/serverTest/serverTest.o] Error 1
```

File: src/Socket/Socket.cpp [hunk 11]
```diff
@@ -0,0 +1,70 @@
+#include "Socket.hpp"
+
+Socket::Socket(int domain, unsigned short port, int type, int protocol, u_long interface)
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:3]: What is `u_long` ?

File: src/Socket/Socket.cpp [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+{
+	_address.sin_family = domain;
+	_address.sin_port = htons(port);
+	_address.sin_addr.s_addr = htonl(interface);
```
Comment (t-h2o) [inline src/Socket/Socket.cpp:7]: Is `u_long` an `unsigned int` ? 
from `man 3 htonl`:
```c
uint32_t htonl(uint32_t hostlong);
```

Comment (RobinBurri) [reply src/Socket/Socket.cpp:7]: Yes, it's uint32_t, but uint32_t is c++11, I have changed it to a simple unsigned int.
3db56b59f48347824d35ac707610298a88d1d798

File: src/Socket/Socket.cpp (hunk 11 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp]: yes, it is unsigned long, but it has nothing to do here.
I have taken out the interface parameter from Socket constructor
as it is always called with INADDR_ANY anyway.
I call htonl(INADDR_ANY) directly.

2ca2fd267b64c6e6a79c50d21ffdc7e71d956119

File: src/Socket/Socket.cpp (hunk 12 above)
Comment (RobinBurri) [reply src/Socket/Socket.cpp]: changed again :
I call htonl(INADDR_ANY) directly.

File: src/Socket/Socket.cpp [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+{
+	return ntohs(_address.sin_port);
+}
+
+void
+Socket::set_socket_non_blocking()
+{
+	int ret;
+	int val = 1;
+	ret = setsockopt(_sock_id, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));
```
[the remark this answers is not in the document]
Comment (t-h2o) [reply src/Socket/Socket.cpp:64]: > what is the purpose of this function ?!

Did you already take a look on `man 3 setsockopt` ?

[the remark this answers is not in the document]
Comment (RobinBurri) [reply src/Socket/Socket.cpp:64]: It is to make the socket reusable.
You won't have message errors like `the socket is already in use` when you quit the server program and start it again shortly after.

File: src/Socket/Socket.cpp [hunk 14]
```diff
@@ -0,0 +1,70 @@
...
+int
+Socket::get_sock_id() const
+{
+	return _sock_id;
+}
+
+unsigned short
+Socket::get_port() const
+{
+	return ntohs(_address.sin_port);
```
[the remark this answers is not in the document]
Comment (RobinBurri) [reply src/Socket/Socket.cpp:56]: look at that :
 https://beej.us/guide/bgnet/html/#htonsman

**Review by 0xCAF3D0OD — APPROVED** [review]
tout est bon pour moi
